resources:
   metadata:
     name: ibmcloudEnablement
   resourceDefs:
     files:
      - ref: files/install/install.sh
      - ref: files/install/uninstall.sh
      - ref: files/install/values-metadata.yaml
      - ref: files/install/README.md